### ISSUE TITLE
Inconsistency between generated Indvidual and Entity versions – number(ing) of sections

### ISSUE THREAD

**Issue by silverhook** [contributoragreements/ca-cla-chooser#10] opened 2018-06-28 14:37 UTC
Quoting an e-mail we got discussing the issue:

> It seems there is an inconsistency between the generated individual and entity contributor agreements. When selecting "Apache 2.0" as outbound license a paragraph is added to the individual, but not to the entity contributor agreement.
>
> When selecting no commitment for an outbound license, the entity contributor agreement still contains a "4. License obligations by Us", though the numbering of the following paragraphs ignore this paragraph, i.e. there are two paragraphs numbered "4".

**Comment by chaoflow** [comment] 2019-01-16 20:30
This happens when option 5 "no comittment for outbound license" is selected.

**Comment by chaoflow** [comment] 2019-01-30 11:41
Looking at the diff (see below) of individual and entity contributor agreement, it seems they are basically identical apart from the paragraph that should not be in the entity agreement.

The entity agreement displays definitions for *Legal Entity* and *Affiliate*, but *Legal Entity* is only used in *Affiliate* and *Affiliate* is not used anywhere.

Shouldn't these two have different content?

```diff
--- individual.html	2019-01-16 20:20:02.368481389 +0100
+++ entity.html	2019-01-16 20:20:22.424554763 +0100
@@ -1,7 +1,7 @@
 <section class="text-center">
 <h2 id="tmp-title">Contributor Agreement</h2>
 
-<h2 id="tmp-subtitle"><span id="tmp-contributor-type">Individual</span> Contributor <span id="tmp-contributor-exclusivity-1">exclusive</span> License Agreement</h2>
+<h2 id="tmp-subtitle"><span id="tmp-contributor-type">Entity</span> Contributor <span id="tmp-contributor-exclusivity-1">exclusive</span> License Agreement</h2>
 <h2 id="tmp-subtitle-patent">(including the <span id="tmp-patent-option">Traditional Patent License</span> OPTION)</h2>
 </section>
 
@@ -17,7 +17,7 @@
 </p><h3>1. Definitions</h3>
 <p><strong>"You"</strong> means the individual Copyright owner who Submits a Contribution to Us.</p> <!-- New and shorter Definition should be amended in all CA's. -->
 
-<div id="tmp-entity-definitions" style="display: none;">
+<div id="tmp-entity-definitions">
 <p><strong>"Legal Entity"</strong> means an entity that is not a natural person.</p>
 
 <p><strong>"Affiliate"</strong> means any other Legal Entity that controls, is controlled by, or under common control with that Legal Entity. For the purposes of this definition, "control" means (i) the power, direct or indirect, to cause the direction or management of such Legal Entity, whether by contract or otherwise, (ii) ownership of fifty percent (50%) or more of the outstanding shares or securities that vote to elect the management or other persons who direct such Legal Entity or (iii) beneficial ownership of such entity.</p>
@@ -82,7 +82,25 @@
 
 
 
+<section id="tmp-outbound-section-all">
 
+<h3>4. License obligations by Us </h3>
+
+<p id="tmp-outbound-option-1-fsfe">We agree to (sub)license the Contribution or any Materials containing, based on or derived from your Contribution under the terms of any licenses the Free Software Foundation classifies as Free Software License and which are approved by the Open Source Initiative as Open Source licenses.</p>
+
+
+
+
+
+
+
+
+
+<p id="tmp-outbound-media-license">In addition, We may use the following licenses for Documentation in the Contribution: <span id="tmp-media-licenses">____________________</span> (including any right to adopt any future version of a license).</p>
+
+<p id="tmp-outbound-special">We agree to license patents owned or controlled by You only to the extent necessary to (sub)license Your Contribution(s) and the combination of Your Contribution(s) with the Material under the terms of <span id="tmp-licenses-2">any licenses the Free Software Foundation classifies as Free Software licenses and which are approved by the Open Source Initiative as Open Source licenses.</span>.</p>
+
+</section>
 
 <h3><span id="tmp-digit-disclaimer">4.</span> Disclaimer</h3>
```

**Comment by mcjsca** [comment] 2019-04-16 21:16
so the issue is that even with `Outbound License(s) | Not Applicable` there is still this section 4in the documents?

[entity-contributor-license-agreement-1.1-2019-04-16-21_14_59.pdf](https://github.com/contributoragreements/ca-cla-chooser/files/3086913/entity-contributor-license-agreement-1.1-2019-04-16-21_14_59.pdf)

[individual-contributor-license-agreement-1.1-2019-04-16-21_14_56.pdf](https://github.com/contributoragreements/ca-cla-chooser/files/3086915/individual-contributor-license-agreement-1.1-2019-04-16-21_14_56.pdf)

**Comment by step21** [comment] 2020-09-22 15:09
This is likely the same as #17 as when inserting both documents (and the hidden versions) into the document, IDs are doubled, but jQuery treats them according to spec when selecting by ID, which means only the first one gets selected and thus changed.

**Comment by step21** [comment] 2020-10-31 20:32
> It seems there is an inconsistency between the generated individual and entity contributor agreements. When selecting "Apache 2.0" as outbound license a paragraph is added to the individual, but not to the entity contributor agreement.

was fixed in b5343a9ce8b1aa90bfe6f9af1c1c2a7aee7f5597 and b4e57abc0b9eb23fc66db9ec96f08c8befcb2e58

> When selecting no commitment for an outbound license, the entity contributor agreement still contains a "4. License obligations by Us", though the numbering of the following paragraphs ignore this paragraph, i.e. there are two paragraphs numbered "4".

I think this was the same as #17 if I understand it correctly. As far a I can tell, there is now no Outbound section in either of the two agreements. Feel free to reopen/comment if I missed something.

**Closed by step21** 2020-10-31 20:32 UTC

**Comment by silverhook** [comment] 2020-11-06 16:09
I made a quick run and it looks OK, but I did stumble upon an issue where a chosen Documentation license was listed in the summary, but not in the CLA text itself.

Afterwards it even happened that the option to choose the Documentation license did not pop up.

@step21, could you try as well and see if we need to open a new ticket?

**Comment by step21** [comment] 2020-11-06 16:22
I couldn't really replicate this. Could you maybe specify exactly what you chose?

**Comment by silverhook** [comment] 2020-11-06 16:24
Unfortunately it worked OK the next time. It could have been when I tested it with the FLA default.

**Comment by step21** [comment] 2020-11-06 16:25
Or it might have been still in cache or something. Let me know if you notice it again.
