### ISSUE TITLE
CLA vs FLA and copyright option are not preserved when revisiting via link

### ISSUE THREAD

**Issue by chaoflow** [contributoragreements/ca-cla-chooser#14] opened 2019-01-16 20:04 UTC
At least the following information is not preserved when revisiting a filled in license agreement via the link displayed at the end:
- CLA vs FLA selection on first page (General)
- Option selected on second page (Copyright)

**Comment by chaoflow** [comment] 2019-01-16 20:23
## Example

The following link should produce the same content as recorded in the screenshots below during creation, but doesn't.

http://contributoragreements.org/ca-cla-chooser/?beneficiary-name=Foo&project-name=bar&project-website=baz&project-email=x&process-url=y&project-jurisdiction=z&agreement-exclusivity=exclusive&fsfe-compliance=&fsfe-fla=&outbound-option=no-commitment&outboundlist=&outboundlist-custom=&medialist=____________________&patent-option=Traditional&your-date=&your-name=&your-title=&your-address=&your-patents=&pos=apply&action=

![page1](https://user-images.githubusercontent.com/89596/51276245-7d739a00-19d4-11e9-9f73-04f4a8d0fc31.png)
![page2](https://user-images.githubusercontent.com/89596/51276246-7e0c3080-19d4-11e9-97f0-ae07c6991600.png)
![page3](https://user-images.githubusercontent.com/89596/51276247-7e0c3080-19d4-11e9-9414-1a086e252194.png)
![page4](https://user-images.githubusercontent.com/89596/51276248-7e0c3080-19d4-11e9-9399-6f85053cebc3.png)
![page5](https://user-images.githubusercontent.com/89596/51276249-7e0c3080-19d4-11e9-91b2-a39a9b5bbd29.png)

**Comment by silverhook** [comment] 2020-08-05 14:11
This might be what caused also the bug in CLA-Assistant: https://github.com/cla-assistant/cla-assistant/issues/605

**Comment by step21** [comment] 2020-11-03 09:05
As far as I can tell, the option is not properly put into the string and not acted upon even if it were there. As you can see in the string above and a test I made just now, there is `fsfe-compliance` and `fsfe-fla` but is not set to anything, and just briefly looking at it now, it might not be acted upon on page load, even if it was there. For past uses, I do not think there is much I can do about it, as I am assuming that it was the same then.

**Comment by step21** [comment] 2020-12-09 13:17
Initial fix in #31 - still needs to be tested more and cleaned up.
Other options apart from the fsfe-compliance like the copyright are still not shown. What it boils down to - if the query string is loaded, it is loaded into configs, but the corresponding buttons etc are not modified. So as long as nothings is changed the output will be correct, but the buttons will look wrong (which might also be why it redirects to the final page.
@silverhook I have to think about if there is an easy way to do this for all buttons etc.

**Comment by silverhook** [comment] 2020-12-15 16:08
@step21 , sounds good to me. Let me know if I can help with anything.

**Comment by step21** [comment] 2020-12-15 16:11
On closer inspection, maybe there is also just a difference when testing locally, as the server part is then not there. Maybe  you can just try to reproduce after I merged #32 - like if after loading string - which ui is displayed correctly which isn't.

**Comment by silverhook** [comment] 2020-12-15 16:27
Sure, just ping me when it’s done. If I don’t respond in a few days, feel free to e-mail me a quick ping.

**Comment by silverhook** [comment] 2022-01-23 22:23
It seems to be working now (probably has for some time, but I only now checked again).

@step21 , @chaoflow , can you confirm that it works as intended now and we can close this issue?

**Comment by silverhook** [comment] 2022-01-23 22:23
It seems to be working now (probably has for some time, but I only now checked again).

@step21 , @chaoflow , can you confirm that it works as intended now and we can close this issue?

**Comment by silverhook** [comment] 2022-06-01 16:03
@adriaandegroot, @cornelius, would you be so kind to confirm this is indeed working now?

I’d like to have someone else apart from me check it’s actually working, before I close the issue.

**Comment by adriaandegroot** [comment] 2022-06-01 21:37
I went for the FLA, filled in fields on the *General* page, then on the *Copyright* page, selected option 3 and filled in a (bogus) URL. click next, then click previous; the selection and URL is still there. On the *Review* page, I can't see anything **at the top** that reflects the selected option, or the URL that I entered. In the document text, the URL is preserved. If I carry on to the end, the documents include the right URL, but the **recreate** links, both in Markdown and in HTML, don't carry the option-selection or the URL, so they don't recreate the exact same license.

**Comment by adriaandegroot** [comment] 2022-06-01 21:40
E.g. the text contains this:

> More specifically and in strict accordance with the above paragraph, we agree to (sub)license the Contribution or any Materials containing, based on or derived from the Contribution only in accordance with our licensing policy available at: https://example.com/option-3-selected.

But the corresponding URL is [https://contributoragreements.org/ca-cla-chooser/?beneficiary-name=bip&project-name=bop&project-website=https%3A%2F%2Fexample.com&project-email=bop%40example.com&process-url=https%3A%2F%2Fexample.com%2Ffla&project-jurisdiction=Afgelegerije&agreement-exclusivity=exclusive&fsfe-compliance=&fsfe-fla=&outbound-option=fsfe&outboundlist=&outboundlist-custom=&medialist=\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_&patent-option=Traditional&your-date=&your-name=&your-title=&your-address=&your-patents=&pos=apply&action=](https://contributoragreements.org/ca-cla-chooser/?beneficiary-name=bip&project-name=bop&project-website=https%3A%2F%2Fexample.com&project-email=bop%40example.com&process-url=https%3A%2F%2Fexample.com%2Ffla&project-jurisdiction=Afgelegerije&agreement-exclusivity=exclusive&fsfe-compliance=&fsfe-fla=&outbound-option=fsfe&outboundlist=&outboundlist-custom=&medialist=____________________&patent-option=Traditional&your-date=&your-name=&your-title=&your-address=&your-patents=&pos=apply&action=) .. which doesn't include the bogus URL, and creates a document without that licensing policy text.

**Comment by step21** [comment] 2022-11-22 14:35
As a separate 'out there' issue - if you know a good resource or person to learn or ask about adding support to automatically test the end result, i.e. if headings have proper numbering or patent pledge is there when it shouldn't (using selenium or playwright for example) any pointers would also be appreciated.

**Comment by step21** [comment] 2024-05-03 08:42
This was recently adressed in #81. Apologies for it taking quite a while, but there were quite a few things to account for to make sure nothing else broke.

**Closed by step21** 2024-05-03 08:42 UTC
